server:
  port: 8762
  forward-headers-strategy: FRAMEWORK

spring:
  boot:
    admin:
      context-path: sbadmin
      instance-auth:
        enabled: true
        service-map:
          bfast-outbound:
            user-name: PORTAL
            password: password
            
      ui:
        title: Isinovasi Admin
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>Isinovasi Admin</span>

  security:
    user:
      name: admin
      password: Rajawali23

  thymeleaf:
    check-template-location: false
    
logging:
  file:
    name: log/admin.log
  logback:
    rollingpolicy:
      max-file-size: 4MB
      max-history: 10